version: latest
services:
  influxdb:
    build: influxdb:latest
    restart: always
    env_file: msc_config.env
    ports: 
        - '8086:8086'
    volumes:
        - influxdb_data:/var/lib/influxdb
  
  grafana:
    build: grafana:latest
    env_file: msc_config.env
    ports: 
        - 3000:3000
    volumes: 
        - grafana_data:/var/lib/grafana

